name: 'Square Cloud Action'
description: 'Deploy your application to square cloud using Github Actions'
author: 'richaardev'
branding:
  icon: square
  color: gray-dark

inputs:
  token:
    required: true
    description: 'Square Cloud api token'
  command:
    required: true
    description: 'Command you want to execute'
  cwd:
    required: false
    default: "."
    description: 'Command you want to execute'

runs:
  using: 'node20'
  main: 'dist/index.js'
