name: 'Square Cloud Easy Action'
description: 'Deploy your application to square cloud using Github Actions'
author: 'richaardev'
branding:
  icon: square
  color: gray-dark

inputs:
  excludes:
    required: false
    description: 'excludes some files'
    default: '.git'
  token:
    required: true
    description: 'square cloud api token'
  application_id:
    required: true
    description: 'square cloud application id'
  restart:
    required: false
    description: 'restart aplication after upload'

runs:
  using: 'node20'
  main: 'dist/index.js'
