name: 'Square Cloud Action'
description: 'Deploy your application to square cloud using Github Actions'
author: 'richaardev'
branding:
  icon: square
  color: gray-dark

inputs:
  token:
    required: true
    description: 'Square Cloud API token'
  command:
    required: true
    description: 'Arguments to pass to Square Cloud CLI'
  workdir:
    required: false
    default: "."
    description: 'Working Directory'

runs:
  using: 'node20'
  main: 'dist/index.js'
